[features]
seeds = false
skip-lint = false

[programs.localnet]
tmm_staking = "2oXApx9k2sPsCdDbQRhbxwzQxm4nrVz3SXK1CorL1FhL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/mdg/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
